export const chh = {
    "sAlternatePTclass": {},
    "arrivalTime": "04:55",
    "atasOpted": false,
    "avlClasses": {
        "Array": [
            "2A",
            "3A",
            "3E",
            "SL"
        ]
    },
    "avaiblitycache": {
        "2A": {
            "TrainNo": "13121",
            "Date": "2024-07-21T00:00:00",
            "Source": "KOAA",
            "Destination": "PNBE",
            "TravelClass": "2A",
            "Quota": "GN",
            "Availability": "GNWL13/WL5",
            "Prediction": "90% Chance",
            "CacheTime": "2024-07-21T12:48:25.001",
            "ConfirmTktStatus": "Confirm",
            "Fare": "1230",
            "Id": -1,
            "AvailabilityDisplayName": "WL 5",
            "PredictionDisplayName": "90% Chance",
            "AvailabilityDataSource": "Ctkt"
        },
        "3A": {
            "TrainNo": "13121",
            "Date": "2024-07-21T00:00:00",
            "Source": "KOAA",
            "Destination": "PNBE",
            "TravelClass": "3A",
            "Quota": "GN",
            "Availability": "GNWL30/WL11",
            "Prediction": "89% Chance",
            "CacheTime": "2024-07-21T12:48:19.001",
            "ConfirmTktStatus": "Confirm",
            "Fare": "870",
            "Id": -1,
            "AvailabilityDisplayName": "WL 11",
            "PredictionDisplayName": "89% Chance",
            "AvailabilityDataSource": "Ctkt"
        },
        "3E": {
            "TrainNo": "13121",
            "Date": "2024-07-21T00:00:00",
            "Source": "KOAA",
            "Destination": "PNBE",
            "TravelClass": "3E",
            "Quota": "GN",
            "Availability": "GNWL39/WL7",
            "Prediction": "90% Chance",
            "CacheTime": "2024-07-21T12:43:07.001",
            "ConfirmTktStatus": "Confirm",
            "Fare": "795",
            "Id": -1,
            "AvailabilityDisplayName": "WL 7",
            "PredictionDisplayName": "90% Chance",
            "AvailabilityDataSource": "Ctkt"
        },
        "SL": {
            "TrainNo": "13121",
            "Date": "2024-07-21T00:00:00",
            "Source": "KOAA",
            "Destination": "PNBE",
            "TravelClass": "SL",
            "Quota": "GN",
            "Availability": "GNWL111/WL29",
            "Prediction": "82% Chance",
            "CacheTime": "2024-07-21T13:12:44.001",
            "ConfirmTktStatus": "Confirm",
            "Fare": "320",
            "Id": -1,
            "AvailabilityDisplayName": "WL 29",
            "PredictionDisplayName": "82% Chance",
            "AvailabilityDataSource": "Ctkt"
        }
    },
    "avaiblitycacheTq": {},
    "departureTime": "20:05",
    "distance": 534,
    "duration": "08:50",
    "flexiFlag": false,
    "fromStnCode": "KOAA",
    "fromStnName": null,
    "runningFri": "N",
    "runningMon": "N",
    "runningSat": "N",
    "runningSun": "Y",
    "runningThu": "N",
    "runningTue": "N",
    "runningWed": "N",
    "toStnCode": "PNBE",
    "toStnName": null,
    "trainName": "KOAA GCT EXPRES",
    "trainNumber": "13121",
    "trainType": [
        "SP"
    ],
    "departureDate": null,
    "sNo": 0,
    "noOfDaysRun": 2,
    "HasPantry": false,
    "IsTejas": false,
    "isDeparted": false,
    "dontShowTatkalOutSideArp": false,
    "VikalpPrediction": "",
    "distanceFromSource": null,
    "distanceFromDestination": null
}